# Generated by Django 5.2.7 on 2025-10-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto_perfil',
            field=models.TextField(default='nada'),
            preserve_default=False,
        ),
    ]
