# Generated by Django 5.2.7 on 2025-10-31 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cliente_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='foto_perfil',
        ),
    ]
